{% set version = "2.6.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinystan
  version: {{ version|replace("-", "_") }}

source:
  fn: shinystan_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinystan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinystan/shinystan_{{ version }}.tar.gz
  sha256: a084856a2d66d8744f2c72e3e19ca35e600a508ed7ef1f7ebed8c7fc0738d529

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dt >=0.2
    - r-bayesplot >=1.5.0
    - r-colourpicker
    - r-dygraphs >=1.1.1.2
    - r-ggplot2 >=2.1.1
    - r-gridextra
    - r-gtools
    - r-markdown >=0.7.4
    - r-reshape2
    - r-rsconnect >=0.4.2
    - r-rstan >=2.17.1
    - r-shiny >=1.0.3
    - r-shinyjs >=0.6.0
    - r-shinythemes >=1.0.1
    - r-threejs >=0.2.1
    - r-xtable
    - r-xts >=0.9_7
  run:
    - r-base
    - r-dt >=0.2
    - r-bayesplot >=1.5.0
    - r-colourpicker
    - r-dygraphs >=1.1.1.2
    - r-ggplot2 >=2.1.1
    - r-gridextra
    - r-gtools
    - r-markdown >=0.7.4
    - r-reshape2
    - r-rsconnect >=0.4.2
    - r-rstan >=2.17.1
    - r-shiny >=1.0.3
    - r-shinyjs >=0.6.0
    - r-shinythemes >=1.0.1
    - r-threejs >=0.2.1
    - r-xtable
    - r-xts >=0.9_7

test:
  commands:
    - $R -e "library('shinystan')"           # [not win]
    - "\"%R%\" -e \"library('shinystan')\""  # [win]

about:
  home: http://mc-stan.org/, http://discourse.mc-stan.org
  license: GPL (>= 3)
  summary: A graphical user interface for interactive Markov chain Monte Carlo (MCMC) diagnostics and plots and tables helpful for analyzing a posterior sample. The interface is powered by the 'Shiny' web application framework from 'RStudio' and works with the output of MCMC  programs written in any programming language
    (and has extended  functionality for 'Stan' models fit using the 'rstan' and 'rstanarm'  packages).
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
