travis:
  secure:
    BINSTAR_TOKEN: ldnuGz1TRElu5bcbTSrpStLfO0JKbwJ4oxhu1FRUPInkITxb3ydiuT3097vhLV7RrSo8qHkCUXdmXZW4hjMEt0LLMNYk8WMNW9j1sxHX58VAakwebvjbkD0yk7IPFssdsW0Pvld0CeVhmLKNg1eHVG3kGYICjF1x+O6nc5jtHS0LqcBES0a7P5ElHC1kYzl55tovajHjHWI7GLpjfARk3ArWMuonqOv+K2/Wv/vKneaouGN6/FD7gwN1yTX6g604rBHWzuWjn5R4FfacJ7cEvvfk1khEaLLbAhcxM5MGKVP5krbePZdmalRbX5OGf6i0uqSbcSdYn6Y8yIEKoI5TojDRaO+SDU86QkhULvAwBpQpcu+eImW2Zwnnn+XFMuXgoWnG7pglq/quzjbSdBHnLsTjvG2200+xifnmr8EJiZo+eQ707o81+SoMYhTJHqw03HYRBMRCoZR0ToPrdoQf3TLzH+9ynHywiSpxwNO7AhbWUu592uysBOxP3xjIM1LkC/GalHMry6nFWe3rFKIYHn4DHCUuVQq6njwdSKjPIaRjGJ/gjbXRQZw4rHoxcIeIKS5yr7qPZ4rccNxbmrgPG6Q0ClwYA+jvr1UJedgdpsvTVq1rJeUiTQR6Ppo7+UYmmBILYZFvGvPuB7ZUA16IwV0Y3rcvhMQ9nuahj0iFE9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
